### PR TITLE
Buildkite pipeline to verify build and publish package

### PR DESCRIPTION
**Pull request by sanjain-progress**
- Build habitat package
- Publish habitat package

### CODE REVIEW

**Comment by tpowell-progress** [comment]
@sanjain-progress don't forget `git commit -s` to DCO your commits

**Review by jaymzh — CHANGES_REQUESTED** [review]
This seems mostly OK, but I have questions... building these should happen on `main` too, no?

Also, you need DCO.

Also, please updated your edit to add newlines in the final line of your lines.

**Comment by sanjain-progress** [comment]
> This seems mostly OK, but I have questions... building these should happen on `main` too, no?
> 
> Also, you need DCO.
> 
> Also, please updated your edit to add newlines in the final line of your lines.

@jaymzh Yes, all these builds should be against the main branch. We are doing this to create the workstation as a Habitat (hab) package. Raising the changes against the workstation-LTS branch is a precaution to ensure nothing breaks. In the future, we can replace workstation-LTS with main.

**Review by jaymzh — APPROVED** [review]
OK, works for me, but I'd *REALLY* appreciate the Workstation team publishing somewhere this list of alllll the work being pooled up behind this Workstation-LTS branches and what the plan for merging it is.

**Review by nikhil2611 — APPROVED** [review]

**Pull request merged**
