### PR TITLE
Add Ubuntu 22.04 (jammy) support

### PR DESCRIPTION
**Pull request by dtseiler**
## Description
This PR adds support for Ubuntu 22.04 (jammy jellyfish).

- All changes are ported from https://github.com/chefspec/fauxhai/pull/369 from @buck3tsec.

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Chore (non-breaking change that does not add functionality or fix an issue)

## Checklist:

- [x] I have read the **CONTRIBUTING** document.
- [ ] I have run the pre-merge tests locally and they pass.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [ ] All commits have been signed-off for [the Developer Certificate of Origin](https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco).

### CODE REVIEW

**Comment by ramereth** [comment]
@dtseiler looks like you to add the signed-off-by tag to your commits. See the details on the failure with DCO.

**Comment by dtseiler** [comment]
> @dtseiler looks like you to add the signed-off-by tag to your commits. See the details on the failure with DCO.

Thanks for pointing this out @ramereth. I've amended the git commit message to include my own sign-off, although the code change was originally written for the old repo by @buck3tsec as I noted in the original note for this PR.

**Comment by tpowell-progress** [comment]
build kite run is broken @tpowell-progress

**Comment by dtseiler** [comment]
> build kite run is broken @tpowell-progress

Is there anything I need to do to get this moving? I'm not familiar with this utility but I just know that our CI pipeline is broken for Ubuntu 22.04 machines at the moment.

**Comment by tpowell-progress** [comment]
> Is there anything I need to do to get this moving? I'm not familiar with this utility but I just know that our CI pipeline is broken for Ubuntu 22.04 machines at the moment.

Trying to troubleshoot [this breakage](https://buildkite.com/chef-oss/chef-fauxhai-main-verify/builds/58#0189b70f-2d23-446c-be01-c192155f5e13/119-120) ... feels like something simple but I've haven't been able to pin it down yet.

**Comment by tpowell-progress** [comment]
> > Is there anything I need to do to get this moving? I'm not familiar with this utility but I just know that our CI pipeline is broken for Ubuntu 22.04 machines at the moment.
> 
> Trying to troubleshoot [this breakage](https://buildkite.com/chef-oss/chef-fauxhai-main-verify/builds/58#0189b70f-2d23-446c-be01-c192155f5e13/119-120) ... feels like something simple but I've haven't been able to pin it down yet.

Ok @dtseiler found the breakage. Can you rebase on main to pick up the fix? Should be able to merge once you've done that. I have this on my list for follow-up so (likely Monday) can merge.

**Comment by dtseiler** [comment]
When I run `git rebase main` from my branch, it tells me this:

```
dropping 1f4b4eb208705d1f85072728f211047e7968a095 Add Ubuntu 22.04 (jammy) support -- patch contents already upstream
```

and I can't merge after that without pulling from my branch again. I'm not the biggest git wonk, so not sure what I might be doing wrong. I did a `git fetch` first as well to get all the current branch info.

**Comment by dtseiler** [comment]
oh I need to sync my fork, duh

**Comment by tpowell-progress** [comment]
@dtseiler Merged!

**Pull request merged**
