### PR TITLE
Update fetcher to pull from correct repository

### PR DESCRIPTION
**Pull request by ramereth**
The fetcher is still trying to pull from the chefspec org which is no longer being maintained. This updates it so that we pull any new platforms that haven't been released can still be pulled.

In addition, update any remaining references to do the old chefspec org.

Signed-off-by: Lance Albertson <lance@osuosl.org>

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Chore (non-breaking change that does not add functionality or fix an issue)

## Checklist:

- [x] I have read the **CONTRIBUTING** document.
- [x] I have run the pre-merge tests locally and they pass.
- [x] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [x] All commits have been signed-off for [the Developer Certificate of Origin](https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco).

### CODE REVIEW

**Review by sathish-progress — APPROVED** [review]
LGTM

**Review by PrajaktaPurohit — APPROVED** [review]

**Comment by ramereth** [comment]
@vkarve-chef @PrajaktaPurohit please don't forget to cut a release on rubygems

**Comment by vkarve-chef** [comment]
Hi @ramereth, the new gem is published at [fauxhai-chef](https://rubygems.org/gems/fauxhai-chef)

**Comment by ramereth** [comment]
@vkarve-chef why not fauxhai-ng? I thought that was the new name.

**Pull request merged**
